### ISSUE TITLE
Support for xGen

### ISSUE THREAD

**Issue by scottplo** [flareman/homebridge-caddx-interlogix#12]
Hi there, wondering if you will be looking to enhance this for the new xGen range. I have this but when using the plugin I cannot connect. 

Can access my system from a web interface and ultrasync app no problem but using the created user and pin in homebrige cannot get it connecting. 

From the log im getting:  Error: Unrecognized vendor
    at NX595ESecuritySystem.login (/usr/local/lib/node_modules/homebridge-caddx-interlogix/src/NX595ESecuritySystem.ts:82:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Could not process zones; not logged in
Could not process zones; not logged in
Could not process zones; not logged in
Could not process zones; not logged in
Could not process zones; not logged in

Not sure if this is something easily resolved.
Cheers

**Comment by flareman** [comment]
Hi there, xGen models use a variation of the web interface so the plug-in naturally can't connect. I would love to adapt to xGen models but I don't have one at hand for testing. I could try to adapt Chris Caron's work on the original Ultrasync plug-in for Home Assistant to work with Homebridge but that would be a lot of trial and error while porting code from Python to Typescript, and I really don't think that the end result would set an example for quality 😎

Of course, if someone wants to fork the project or submit a pull request, I'm all for it ✌🏻

**Comment by dkossman** [comment]
@scottplo I just took a quick look at the UI code using debug mode in my browser for my NoWa360 leak detection/shutoff panel, which (based on the pictures) I think is based on the Interlogix ZW-6400 UltraSync panel.  not sure if this is the same as "xGen"?  In any case its very different than this current plugin expects.  I am a very neophyte javascript coder but if I have time (which is unlikely)  I'll see how far I can get with a fork.  

see the issue I just closed as a dup for details.

**Comment by flareman** [comment]
ZW means the module uses the ZeroWire firmware, which is a third type different from xGen, and which unfortunately uses different syntax from ComNav versions (that my plugin is made for).

You could try and adapt the original UltraSync code from Chris Caron (@caronc). He has implemented both ZeroWire and xGen support in his code, but it's in Python and needs porting over. Sadly, I don't have the modules necessary to debug properly at hand, but by all means feel free to chew on this ^^.

For the record, Chris has released and still maintains an integration for Home Assistant that uses his library and therefore supports all panel types. Not HomeKit compatible, but it's a good alternative for anyone that needs ZeroWire or xGen support and doesn't mind going outside Apple's system.
