### ISSUE TITLE
New card, new problem

### ISSUE THREAD

**Issue by doncarajo** [flareman/homebridge-caddx-interlogix#19]
Hi again. So I got fed up with this malfunctioning card so I ordered a new card and installed it tonight. It has new firmware and the options are a little different. The biggest problem is that the web access only works when the panel is in program mode, this is supposed to be a security feature. Reading the manual (https://assets.hills.com.au/p/ComNavInstallationManual.pdf), it says that if option 6 is turned on, then web access will be on permanently...except that when I do that, it still doesn't work unless the panel is in program mode. This is so frustrating. Any ideas?

**Comment by doncarajo** [comment]
I should add that I can access the panel using the ultrasync+ app, but this is obviously suboptimal as it's using their servers.

**Comment by flareman** [comment]
In the installers' manual, page 39, it mentions the web access option as Location 19, segment 1, option 8. Maybe the instructions mentioned in page 43 have a typo? Also, take a look at the Network Settings page in the web interface, and in particular check the Enable Web Access option; maybe that is the web equivalent? I have no idea how to program the module, my technician did it for me so I avoid tampering too much with it; just my 2¢ here ^^

**Comment by doncarajo** [comment]
Yes, both options are enabled. I thought you might have known something about it. I have sent an email to the supplier.
