### ISSUE TITLE
[Bug] Spaces in names appear as %20

### ISSUE THREAD

**Issue by BeauGiles** [flareman/homebridge-caddx-interlogix#2]
Any spaces in names (Area, etc) are shown as %20 in HomeKit.

eg, "Central Street" will show as "Central%20Street"

(This is the Hills Comnav (S2096A))

**Comment by flareman** [comment]
Thanks for the report. Does this affect zone/sensor names as well? Zones have their names URI-decoded on load, so theoretically this should not affect those. For areas I don't have that issue, but I have an idea where this could have gone wrong, a fix should be easy enough.

**Comment by BeauGiles** [comment]
After checking again it seems to only affect the 'Area' names.

An area named 'Central Street' will show as 'Central%20Street' in Home.

Zones doesn't have these same issue - 'Lounge Room' correctly shows as 'Lounge Room'

**Comment by flareman** [comment]
Ok, it should work now. Please update and let me know.

**Comment by BeauGiles** [comment]
Not sure if related to the update, but after the update I have a handful of alarms named '!'

(I renamed my alarm to 'Alarm')

[06/01/2021, 21:44:38] [Hills CommNav] Restoring existing accessory from cache: Alarm
[06/01/2021, 21:44:38] [Hills CommNav] Adding new accessory: !
[06/01/2021, 21:44:38] [Hills CommNav] Adding new accessory: !
[06/01/2021, 21:44:39] [Hills CommNav] Adding new accessory: !
[06/01/2021, 21:44:39] [Hills CommNav] Adding new accessory: !
[06/01/2021, 21:44:39] [Hills CommNav] Adding new accessory: !
[06/01/2021, 21:44:39] [Hills CommNav] Adding new accessory: !
[06/01/2021, 21:44:39] [Hills CommNav] Adding new accessory: !

**Comment by flareman** [comment]
v1.0.2 is up, it should fix this too. Would you please check and let me know?

Apologies for the back and forth, I am outside of home at present and trying to bug fix on the move :)

**Comment by BeauGiles** [comment]
I can confirm v1.0.2 seems to fix both the '!' accessories (after removing the accessories in the Homebridge web UI) and the %20 in area names.

**Comment by flareman** [comment]
Great! Thanks for the input 👍
