### ISSUE TITLE
Output 1 switch no longer opens garage door since 1.2.9

### ISSUE THREAD

**Issue by muratwrx** [flareman/homebridge-caddx-interlogix#21]
my output switch 1 is wired to open the garage door and up until version 1.2.8 - this was working perfectly. However since version 1.2.9 and onwards - when you switch on the Output 1 via homebridge, it no longer opens the garage door. I have tried deleting the plugin and install a fresh version of 1.2.9 or 1.3.0 and still no luck. Is there anything I can provide you to help trouble shoot this please?

**Comment by flareman** [comment]
Thanks for the heads up. No need for details, I found the bug. Please stand by for v1.3.1 which will release later today and will fix it :)

**Comment by flareman** [comment]
Please try out v1.3.1 and let me know if it's okay for you :)

**Comment by muratwrx** [comment]
Amazing, thank you so much - i have installed and tested v1.3.1 and is working perfectly. Thank you for the amazing work.
