### ISSUE TITLE
Feature suggestions

### ISSUE THREAD

**Issue by JoHoop** [flareman/homebridge-caddx-interlogix#5]
I have some suggestions for the future.
I'd be happy to help implementing them. :)

- [x] allow ungrouping of accessories (contact sensor and it's bypass switch) to show them as different tiles in Apple Home (so you could see the sensors and group all bypass switches)
- [x] display radar accessories as motion sensors (instead of contact sensors)
- [x] display smoke detector accessories (instead of contact sensors)

**Comment by flareman** [comment]
> - [x] allow ungrouping of accessories (contact sensor and it's bypass switch) to show them as different tiles in Apple Home (so you could see the sensors and group all bypass switches)

This can be done, although for big installations it might lead to a whole mess of accessories in Home.app - maybe grouping all bypass switches in one accessory might be a more clean solution?

> - [x] display radar accessories as motion sensors (instead of contact sensors)

The plugin already supports setting radars as such manually in its settings. Unfortunately, the system does not appear to have any inner knowledge of what kind of sensor a zone is - at least for radars (there is no flag for radar status AFAIK). The manual option works nicely, however, and allows for manual name overrides as well for older setups where the user can't set zone names in the web interface.

> - [x] display smoke detector accessories (instead of contact sensors)

I don't have smoke sensors in my installation to test. If you do have some in your setup, please grab an instance of your zones array and point out said sensors; I could check whether there is some kind of flag for this. I sincerely doubt that the system knows which sensors are smoke detectors, just like with the radars; however, it should be easy to implement them via the manual override described above.

**Comment by JoHoop** [comment]
> maybe grouping all bypass switches in one accessory might be a more clean solution?

I agree! What would be the best way to do that? :)

> The plugin already supports setting radars as such manually in its settings.

Thanks, that's working nicely!!
 
> I sincerely doubt that the system knows which sensors are smoke detectors, just like with the radars; however, it should be easy to implement them via the manual override described above.

Unfortunately, there's no way to tell the kind of sensor.
But I could try to add the manual override option and create a PR?

**Comment by flareman** [comment]
For the smoke sensors, you would need to create a new subclass in platformAccessory.ts describing the smoke sensor accessory with all its logic, add the choice for smoke sensor in the config options and then add the logic necessary in accessory discovery to set the zones described as such.

Grouping bypass switches is a bit more complex: normally accessories support only one kind of service per type, so in order to group all bypasses in one accessory, we should create duplicates of the switch service with different handles for every sensor, then make sure that every sensor gets one such service in the grouped accessory. It's not that simple but theoretically it can be done.

**Comment by JoHoop** [comment]
> It's not that simple but theoretically it can be done.

Perhaps it would be easier to allow ungrouping or somehow enable the `Show as Separate Tiles` functionality. (This is working for the security area accessory)

That would allow the manual setup of the group for bypass switches.

<img width="510" alt="Screenshot 2021-02-14 at 17 23 55" src="https://user-images.githubusercontent.com/67421398/107882410-6bcd8b00-6ee9-11eb-861d-d8736f1047e9.png">

**Comment by flareman** [comment]
> Perhaps it would be easier to allow ungrouping or somehow enable the `Show as Separate Tiles` functionality. (This is working for the security area accessory)
> 
> That would allow the manual setup of the group for bypass switches.

The security area accessory and the sensors accessories are set up in the same way (multiple services set up under the same accessory), so it's probably a matter of how HomeKit groups these accessories. You can group the bypass switches under one "master" bypass switch (go into the sensor accessory, scroll down and find the Accessories submenu, then tap on the switch and scroll down to find the Group Accessories option) - however, this creates an additional switch that can be seen from all rooms where there are sensors, does not make individual sensor accessories disappear, and you have to long press it to access individual switches (which defeats the purpose of grouping).

Given the way HomeKit works now, the only way to truly separate sensors from switches is to set them up in the plugin as separate accessories. Again, as I said, not impossible, but needs substantially more work 🤷

**Comment by flareman** [comment]
Hello,

Regarding your former requests, smoke sensors overrides can be set now with versions above 1.1.0.

Please update and enjoy :)

**Comment by JoHoop** [comment]
Thanks so much @flareman great stuff!!

I was wondering if it would be possible to not create any bypass switches at all.
So that the sensor states are not grouped with the bypass switches? :)

**Comment by flareman** [comment]
Version 1.1.4 is live which adds a new optional setting for hiding bypass switches altogether :)

**Comment by JoHoop** [comment]
you are amazing!! I couldn't be happier!! :D
