### ISSUE TITLE
NX 584 integration

### ISSUE THREAD

**Issue by farberm** [flareman/homebridge-caddx-interlogix#9]
I have an NX 584 board that connects via a serial to tcp connector  on ipaddress:    x.x.x.:4999. Can this plug-in communicate that way or be modified to communicate to the NX584 board….I am pretty sure all the 595 boards are sold out

thanks.

**Comment by flareman** [comment]
NX-584 connects using a serial interface, so the plugin does not support that interface. There are a couple of plugins available for homebridge, however, that might be able to do what you want, either as standalone homebridge plugins, or as add-ons to the AlarmDecoder plugin.
